<?xml version="1.0"?>
<sdf version="1.6" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="landmark" params="id *pose">
   
    <xacro:property name="pole_above_ground" value="0.3"/>
    <xacro:property name="box_width" value="0.25"/>
    <xacro:property name="pole_below_ground" value="0.1"/>
    <xacro:property name="box_height" value="0.32"/>
    <xacro:property name="sheet_width" value="0.005"/> <!-- When the sheet is too thin it is not shaded properly for some reason -->
    <xacro:property name="sheet_out" value="0.001"/>

    <model name="landmark${id}">
      <xacro:insert_block name="pose"/>
      <static>true</static>

      <link name="landmark">
        <visual name="pole_visual">
          <pose>0 0 ${(pole_above_ground - pole_below_ground)/2} 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>${pole_above_ground + pole_below_ground}</length>
            </cylinder>
          </geometry>
          <material>
            <script>
              <name>Gazebo/Wood</name>
            </script>
          </material>
        </visual>
        <collision name="pole_collision">
          <pose>0 0 ${(pole_above_ground - pole_below_ground)/2} 0 0 0</pose>
          <geometry>
            <cylinder>
              <radius>0.01</radius>
              <length>${pole_above_ground + pole_below_ground}</length>
            </cylinder>
          </geometry>
        </collision>

        <visual name="box_visual">
          <pose>0 0 ${pole_above_ground + box_height/2} 0 0 0</pose>
          <geometry>
            <box>
              <size>${box_width} ${box_width} ${box_height}</size>
            </box>
          </geometry>
          <material>
            <script>
              <name>ERC_Landmark/Box</name>
            </script>
          </material>
        </visual>
        <collision name="box_collision">
          <pose>0 0 ${pole_above_ground + box_height/2} 0 0 0</pose>
          <geometry>
            <box>
              <size>${box_width} ${box_width} ${box_height}</size>
            </box>
          </geometry>
        </collision>

        <xacro:macro name="landmark_sheet" params="name *pose">
          <visual name="${name}">
            <xacro:insert_block name="pose"/>
            <geometry>
              <box>
                <size>0.21 ${sheet_width} 0.297</size>
              </box>
            </geometry>
            <material>
              <script>
                <name>ERC_Landmark/${id}</name>
              </script>
            </material>
          </visual>
        </xacro:macro>

        <xacro:landmark_sheet name="sheet1">
          <pose>0 ${(box_width - sheet_width)/2 + sheet_out} ${pole_above_ground + box_height/2} 0 0 0</pose>
        </xacro:landmark_sheet>

        <xacro:landmark_sheet name="sheet2">
          <pose>0 -${(box_width - sheet_width)/2 + sheet_out} ${pole_above_ground + box_height/2} 0 0 0</pose>
        </xacro:landmark_sheet>

        <xacro:landmark_sheet name="sheet3">
          <pose>${(box_width - sheet_width)/2 + sheet_out} 0 ${pole_above_ground + box_height/2} 0 0 ${pi/2}</pose>
        </xacro:landmark_sheet>

        <xacro:landmark_sheet name="sheet4">
          <pose>-${(box_width - sheet_width)/2 + sheet_out} 0 ${pole_above_ground + box_height/2} 0 0 ${pi/2}</pose>
        </xacro:landmark_sheet>

      </link>
    </model>
  </xacro:macro>
</sdf>
